# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f4bced15c1e1889c812d62e9df8580d49f36d7ae2bf459888fc62d9c41181c5e22348a9d5f6f58fdc8e329e569468c25d4cd6e1ad64506d4e41845468551fe

test:
  secret_key_base: 4db7f5ea4b4f87752484bbbadd2326a64e99d1f2272a3624d7ecde4bc066fe4d9f9252b826c224e6f6e2a57561282f111305d33fa882ac2f25ef25009db5212c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
